name: presubmit
on:
  push:
  pull_request:
  schedule:
    - cron: "0 18 * * *"
jobs:
  presubmit:
    name: Presubmit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Fetch toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
          target: thumbv6m-none-eabi
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: ${{ matrix.toolchain }}
      - name: Build no-std
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target thumbv6m-none-eabi
          toolchain: ${{ matrix.toolchain }}
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          toolchain: ${{ matrix.toolchain }}
      - name: Install cargo-audit binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
